#
# Makefile
# Build a simple Nokia 5110 LCD demo for the MSP430 LaunchPad.
#
ENERGIADIR = /Applications/Energia.app/Contents/Resources/Java
#ENERGIAMK_DIR = /usr/local/share/energia-mk
ENERGIAMK_DIR = /Users/jay/Development/energia-makefile

ENERGIABOARD = lpmsp430g2553
SERIALDEV = /dev/tty.uart*
LIBRARIES = SPI

include ${ENERGIAMK_DIR}/energia.mk
